// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion: dynamic(() => import("./Accordion")),
  call_to_action: dynamic(() => import("./CallToAction")),
  carousel: dynamic(() => import("./Carousel")),
  image_text: dynamic(() => import("./ImageText")),
  logo_list: dynamic(() => import("./LogoList")),
  map: dynamic(() => import("./Map")),
  menu_panel: dynamic(() => import("./MenuPanel")),
  multi_link: dynamic(() => import("./MultiLink")),
  numbered_list: dynamic(() => import("./NumberedList")),
  rich_text: dynamic(() => import("./RichText")),
  simple_text: dynamic(() => import("./SimpleText")),
  single_link: dynamic(() => import("./SingleLink")),
  testimonial: dynamic(() => import("./Testimonial")),
  tile_grid: dynamic(() => import("./TileGrid")),
};
